{
  pkgs,
  preCommit,
}:
let
  /*
    The two facts the launchers bake in. `nix/pre-commit.nix` is their owner — `installStages` and
    `configPath` fall out of the hook set it declares — but the launchers must exist before
    `pre-commit-lib.run` is evaluated, because one of that run's own hooks proves them. Restating
    them here would be a duplicate, so `shellHookFor` asserts the two answers agree and fails the
    evaluation rather than installing a launcher for a stage nothing runs.
  */
  hookTypes = [
    "pre-commit"
    "commit-msg"
  ];
  configPath = ".pre-commit-config.yaml";

  /*
    One launcher serves every linked worktree, because Git resolves `hooks/` from the COMMON Git
    directory rather than from the worktree it is committing in.

    So the launcher names no worktree AND no revision. Not the worktree, because `--config` stays
    relative and pre-commit resolves it against the working tree Git handed the hook — that
    worktree's own generated config, at that worktree's own revision. Not the revision, because a
    `/nix/store` path in this file (an interpreter, a shebang) differs between two worktrees sitting
    on two `flake.lock`s, and each entry would then rewrite what the other just installed. That is
    the same last-writer-wins defect this replaces, moved from the config to the launcher.

    `writeText` rather than `writeShellScript` for exactly that reason: the latter writes a store
    path as the shebang.
  */
  launcher =
    hookType:
    pkgs.writeText "ferretry-${hookType}-launcher" ''
      #!/usr/bin/env bash
      # Ferretry shared Git hook launcher (generated by nix/git-hooks.nix; do not edit).

      ferretry_hooks_dir="$(cd "$(dirname "$0")" && pwd)"

      # pre-commit's migration mode demotes whatever occupies a hook path to `<hook>.legacy` and then
      # calls it. Aimed at this launcher, that is a call to itself: `--hook-dir` below would find the
      # same `.legacy` again, without limit. The guard therefore carries THIS launcher's own path
      # rather than a bare flag — a bare flag is exported into every nested process, and a `git
      # commit` in another repository underneath this hook would silently run no hooks at all.
      if [ "''${FERRETRY_GIT_HOOK:-}" = "''${ferretry_hooks_dir}/${hookType}" ]; then
        exit 0
      fi
      FERRETRY_GIT_HOOK="''${ferretry_hooks_dir}/${hookType}"
      export FERRETRY_GIT_HOOK

      # Every ordinary commit here is made from a devshell, where PATH already holds the pre-commit
      # this worktree's own revision pins. The link in the common Git directory is the pinned
      # fallback for a commit made outside one; it is resolved through `git` rather than relative to
      # this launcher, because the same launcher is installed both in the common hooks directory and
      # in a private per-worktree one, and those sit at different depths.
      ferretry_pre_commit="$(command -v pre-commit || true)"
      case "''${ferretry_pre_commit}" in
      /nix/store/*) ;;
      *)
        ferretry_common_dir="$(git rev-parse --path-format=absolute --git-common-dir)"
        ferretry_pre_commit="''${ferretry_common_dir%/}/ferretry-pre-commit/bin/pre-commit"
        ;;
      esac

      exec "''${ferretry_pre_commit}" hook-impl \
        --config=${configPath} \
        --hook-type=${hookType} \
        --hook-dir "''${ferretry_hooks_dir}" \
        -- "$@"
    '';

  launchers = pkgs.runCommand "ferretry-git-hook-launchers" { } (
    ''
      mkdir -p "$out"
    ''
    + pkgs.lib.concatMapStrings (hookType: ''
      install -m 0755 ${launcher hookType} "$out/${hookType}"
    '') hookTypes
  );

  # An explicit PATH, like nix/pre-commit.nix's validator wrapper: the installer runs from a
  # shellHook and must never depend on a host-installed binary. `nix-store` stays on the ambient
  # PATH — the installer degrades to a plain symlink where there is no Nix to pin a GC root with.
  runtime = pkgs.buildEnv {
    name = "ferretry-git-hooks-runtime";
    paths = [
      pkgs.coreutils
      pkgs.diffutils
      pkgs.findutils
      pkgs.gawk
      pkgs.git
      pkgs.gnugrep
      pkgs.gnused
    ];
  };

  installScript = ./git-hooks/install.sh;
in
{
  inherit hookTypes launchers runtime;

  shellHookFor =
    {
      configFile,
      generatedConfigPath,
      installStages,
    }:
    assert pkgs.lib.assertMsg (installStages == hookTypes)
      "nix/git-hooks.nix installs ${builtins.toJSON hookTypes}, but nix/pre-commit.nix asks for ${builtins.toJSON installStages}";
    assert pkgs.lib.assertMsg (generatedConfigPath == configPath)
      "nix/git-hooks.nix resolves ${configPath}, but nix/pre-commit.nix generates ${generatedConfigPath}";
    ''
      PATH=${runtime}/bin:$PATH ${pkgs.bash}/bin/bash ${installScript} ${launchers} ${configFile} ${preCommit}
    '';
}
