/** Stable role exposed by this workspace package. */
export const packageRole = 'daemon' as const;

export * from './analytics/model-identity.ts';
export * from './analytics/pricing.ts';
export * from './analytics/query.ts';
export * from './analytics/results.ts';
export * from './analytics/session-record.ts';
export * from './attachments/index.ts';
export * from './attention/index.ts';
export * from './browser/control/index.ts';
export * from './browser/transport/index.ts';
export * from './instant.ts';
export * from './journal.ts';
export * from './json.ts';
export * from './layout.ts';
export * from './learning/index.ts';
export * from './migrate/verdict.ts';
export * from './names/index.ts';
export * from './paths.ts';
export * from './pins/index.ts';
export * from './ports.ts';
export * from './rebuild.ts';
export * from './reconciliation.ts';
export * from './runtime/index.ts';
export * from './session-id.ts';
export * from './session/lifecycle/index.ts';
export * from './state-home.ts';
export * from './storage-types.ts';
export * from './task-boards/index.ts';
export * from './tasks/index.ts';
export * from './terminal/index.ts';
export * from './tmux/index.ts';
export * from './version.ts';
export * from './warden/index.ts';
export * from './worktrees/index.ts';
