# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferretry" do
  version "0.92.1"

  on_macos do
    on_arm do
      sha256 "5c3d3091a6d5f9d28e8ff3eef7dc788eeb718bb38665a5fe1d9f77c72fe243cf"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "706eba1b9d2f78568a90c562c7f647a70907d15d52966eda93e63a2a7d6fe1b1"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e23caf601db103a7e620b06d33db3bc5a9cc686e6b5ac082cc23e649a8c4378d"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_linux_arm64.tar.gz"
    end
  end

  name "ferretry"
  desc "Command-line client for the per-host agent daemon"
  homepage "https://github.com/kirinnee/ferretry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fy"]
    end
  end

  # No zap stanza required

end
