# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferretry" do
  version "0.172.0"

  on_macos do
    on_arm do
      sha256 "67bfd2ec7174c564b329c998728d14744203771b1e051d46dcb8755434d68e8a"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ff6f0a09b60b1ca2355353007b5d0388dd204c8b14c8a7bf50ea2fddfb365c0"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1fb69c2e554d692516fdfe66fb16078235c489f22d7ac5715044cafbe09f1c08"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_linux_arm64.tar.gz"
    end
  end

  name "ferretry"
  desc "Command-line client for the per-host agent daemon"
  homepage "https://github.com/kirinnee/ferretry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fy"
  binary "fyd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fy", "#{staged_path}/fyd"]
    end
  end

  # No zap stanza required

end
