# This file was generated by GoReleaser. DO NOT EDIT.
cask "ferretry" do
  version "3.6.0"

  on_macos do
    on_arm do
      sha256 "9e9c7ce5f24e1f1170205220df1acb6d756b32c0845210a479478ee3cf73c752"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "837037fd0fcc124a6d0991bf327b037dfc34e23320a0b7e55645d7f69c854ae1"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9be26c2bc8b2d5cc2ff90cd6c62abb685f53f87a22a361b413fb2621baae142c"
      url "https://github.com/kirinnee/ferretry/releases/download/v#{version}/fy_linux_arm64.tar.gz"
    end
  end

  name "ferretry"
  desc "Command-line client for the per-host agent daemon"
  homepage "https://github.com/kirinnee/ferretry"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fy"
  binary "fyd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fy", "#{staged_path}/fyd"]
    end
  end

  # No zap stanza required

end
