#!/usr/bin/env bash
set -euo pipefail

root_dir="$(git rev-parse --show-toplevel)"
cd "${root_dir}"

./scripts/validate/pages-config.sh

cd packages/pwa
bun install --frozen-lockfile

cd "${root_dir}"
task build:pwa

test -f packages/pwa/dist/_headers
test -f packages/pwa/dist/_redirects

# The `fy-render` sandbox shell and its two library bundles are GENERATED by
# `bun run build:fy-render-shell`, which the package build chains ahead of Vite.
# Assert they reached `dist` rather than trusting that chain: if generation ever
# stops running, the deploy ships a 404 shell, every diagram and animation
# degrades silently to its source text, and nothing else in this pipeline fails.
for asset in fy-render-sandbox.html fy-render-mermaid.js fy-render-lottie.js; do
  test -s "packages/pwa/dist/${asset}" || {
    echo "❌ packages/pwa/dist/${asset} is missing or empty; the fy-render shell was not generated" >&2
    exit 1
  }
done
cmp packages/pwa/public/_headers packages/pwa/dist/_headers
cmp packages/pwa/public/_redirects packages/pwa/dist/_redirects

echo "✅ PWA static bundle and Pages headers are ready"
