#!/usr/bin/env bash
set -euo pipefail

# The `fy-render` sandbox shell, proved in real Safari on a real macOS window server.
#
# WHY THIS IS A SCRIPT UNDER scripts/ci AND NOT A VALIDATOR OR A TEST.
# `scripts/validate/contract-registry.sh` compares the set of `scripts/validate/*.sh` against the
# README validator table AND the pre-commit wiring, so a validator here would force a pre-commit hook
# — and pre-commit runs on Linux, where Safari does not exist. A `bun test` file is worse: the int
# tier runs on `ubuntu-latest`, so it would either fail on a runner with no `/usr/bin/safaridriver` or
# be written to skip when Safari is absent, which is a green that proves nothing. `scripts/ci/` is
# outside the contract registry, and this program never enters a coverage ledger.
#
# WHY IT REFUSES TO RUN ANYWHERE BUT DARWIN, RATHER THAN SKIPPING.
# A skip that exits 0 is indistinguishable from a pass in every CI summary anybody reads. Exit 2 says
# "this gate did not run", which is a different fact from "this gate passed", and the job that invokes
# it only exists on `macos-15`.
#
# `safaridriver` HAS NO HEADLESS MODE — its man page documents `-p/--port`, `--enable`, `--diagnose`,
# `--version` and nothing else — and Safari hosts exactly ONE WebDriver session at a time. So this
# runs headed, in the runner's autologin GUI session, strictly sequentially. Do not parallelise it:
# the symptom is flaky session-creation failures that look like product defects.
#
# Local use on a Mac:
#   sudo safaridriver --enable        # once per machine; prompts for a password
#   ./scripts/ci/safari-render-proof.sh
#
# Anywhere, including Linux, for everything that does not need a browser:
#   ./scripts/ci/safari-render-proof.sh --self-check

root_dir="$(git rev-parse --show-toplevel)"
cd "${root_dir}"

probe="packages/pwa/harness/fy-render-safari/probe.ts"

# The self-check needs no browser and no platform, so it is answered before the Darwin gate. It
# verifies policy extraction, hash byte order, probe-document construction, the `_headers` reader,
# request classification, the ledger's positive control, the production parser against the probe's own
# replies, the artifact schema and the WebDriver client's teardown. It scores no journey property and
# it is not Safari evidence.
if [ "${1:-}" = "--self-check" ]; then
  echo "🧪 Checking the fy-render Safari harness without a browser..."
  exec bun "${probe}" --self-check
fi

if [ "$(uname -s)" != "Darwin" ]; then
  echo "❌ this proof needs Safari, which only exists on macOS." >&2
  echo "   Run it on a Mac or on the CI job's macos-15 runner." >&2
  echo "   For the parts that need no browser: ./scripts/ci/safari-render-proof.sh --self-check" >&2
  exit 2
fi

if ! command -v safaridriver >/dev/null 2>&1; then
  echo "❌ safaridriver is not on PATH; it ships with Safari at /usr/bin/safaridriver." >&2
  exit 2
fi

# Idempotent and free, and it is the exact pair of steps every "Could not create a session: You must
# enable the 'Allow Remote Automation' option" thread ends at. The GitHub macOS image already does
# both at build time; re-running makes a developer's Mac behave like the runner.
if [ "${FY_RENDER_SAFARI_SKIP_ENABLE:-}" != "1" ]; then
  sudo safaridriver --enable
fi

plist="${HOME}/Library/WebDriver/com.apple.Safari.plist"
if ! /usr/libexec/PlistBuddy -c 'print AllowRemoteAutomation' "${plist}" 2>/dev/null | grep -q true; then
  echo "❌ AllowRemoteAutomation is not true in ${plist}." >&2
  echo "   Run: sudo safaridriver --enable" >&2
  exit 2
fi

./scripts/ci/setup.sh

echo "🧪 Proving the fy-render sandbox shell in Safari on $(uname -sm)..."
# The probe generates the shell itself, so it always measures freshly generated bytes rather than a
# stale artifact somebody left in `public/`.
bun "${probe}" "$@"
echo "✅ The fy-render sandbox shell holds in Safari; the evidence ledger is in packages/pwa/.artifacts/safari-render/"
