/**
 * The one place a fleet profile's credential becomes a value, and the only thing it is handed to is
 * the launch it was resolved for.
 *
 * ## What this is
 *
 * A profile can authenticate an account instead of a login: it binds an environment variable to
 * `${secret:NAME}`, the fleet manifest publishes that binding as a REFERENCE, and this resolves the
 * reference against the daemon's own store at the moment a pane is launched. `docs/secrets.md` is the
 * contract and `docs/fleet-env-profiles.md` is the feature.
 *
 * ## Why this may hold a vault when almost nothing may
 *
 * `SecretVault` is the only thing in the daemon that opens ciphertext, and until now exactly two
 * things held one: the redactor, which turns values into masks, and the use executor, which puts them
 * in a child's environment and returns only that child's scrubbed output. This is the third, and it
 * is the same kind of thing as the second — it produces an environment for one launch and returns it
 * to the launcher, which passes it straight to the terminal. It answers nothing to a route, projects
 * nothing, logs nothing, and caches nothing. A method here that returned a value to a caller who was
 * going to show it to somebody would delete the property rather than extend it.
 *
 * ## Why the manifest and not the configuration
 *
 * The manifest is the record a start already reads, and it is regenerated by the same apply that
 * writes the wrappers — so it cannot describe an account differently from the wrapper that will run.
 * Reading the fleet CONFIGURATION here instead would make every session start depend on that document
 * parsing, and a host whose `config.yaml` has a typo in it has perfectly good wrappers.
 *
 * ## What it costs when nobody uses a profile
 *
 * Nothing. An account that binds no secret answers `{}` without the store ever being opened, so the
 * overwhelming case — a fleet authenticated by ordinary logins — pays one lookup in a list it already
 * had. That is deliberate: a fresh account has to work with no profile at all.
 */

import { type FleetManifestAccount, resolveSecretEnvironment, wrapperNameOf } from '@ferretry/fleet';
import type { SecretName } from '@ferretry/protocol';

/**
 * The extra environment one account's launch is entitled to, keyed by the executable it runs.
 *
 * A PORT, so the two launch paths depend on the decision rather than on the store. `wrapper` is the
 * absolute published path a session record carries; the name is derived from it the one sanctioned
 * way, so an account is never located by a string somebody assembled.
 */
export interface AccountLaunchEnvironment {
  /** Empty when this executable is not a published account, or the account binds no secret. */
  forWrapper(wrapper: string): Promise<Readonly<Record<string, string>>>;
}

/** The published accounts, as the daemon's existing inventory already answers them. */
export interface LaunchAccountInventory {
  accounts(): Promise<readonly FleetManifestAccount[]>;
}

/** The opening half of the secret store. Structural, so the vault is passed rather than reached for. */
export interface LaunchSecretValues {
  values(): Promise<ReadonlyMap<SecretName, string>>;
}

/**
 * Resolves one account's profile-bound environment for a launch.
 *
 * An account this daemon does not publish answers `{}` rather than refusing. A session may legally
 * run an executable that is not a fleet account — the authorization boundary decides that, and it is
 * not this module's question — and refusing here would turn "I have no opinion" into "you may not
 * start", which is a different answer given by the wrong component.
 *
 * A MISSING SECRET REFUSES THE LAUNCH, and that is the whole design: `resolveSecretEnvironment` raises
 * naming every secret the store does not hold, so the failure arrives at the start, on this machine,
 * naming the thing to fix. The alternative is an empty credential and a 401 from a remote service
 * twenty minutes later with nothing to point at.
 *
 * A DAMAGED STORE ALSO REFUSES, for the same reason it refuses a redaction: a vault that cannot be
 * opened is not a vault with nothing in it, and launching an account as though its profile were empty
 * would silently authenticate it as somebody else — or as nobody.
 */
export class FleetLaunchEnvironment implements AccountLaunchEnvironment {
  constructor(
    private readonly inventory: LaunchAccountInventory,
    private readonly secrets: LaunchSecretValues,
  ) {}

  async forWrapper(wrapper: string): Promise<Readonly<Record<string, string>>> {
    const name = wrapperNameOf(wrapper);
    const account = (await this.inventory.accounts()).find(
      published => wrapperNameOf(published.wrapper) === name || published.wrapper === wrapper,
    );
    if (account === undefined || Object.keys(account.secretEnv).length === 0) return {};
    // Opened only now, and only for an account that declared it needs something. A fleet nobody
    // gave a profile to never touches the store at all.
    return resolveSecretEnvironment({ id: account.id, env: account.secretEnv }, await this.secrets.values());
  }
}

/**
 * The environment a pane is launched with: what the account's profile supplies, then what the session
 * itself owns.
 *
 * THE SESSION WINS. Its own document carries the credential a task board issued it and any variable a
 * grant delivered, and those name that one session; a profile is shared by every account that lists
 * it. A profile able to overwrite them would let one shared document take a teammate's board
 * capability away from it — so the precedence runs the only direction that cannot do that, and the
 * session id the launcher derives afterwards is still written last.
 */
export function launchEnvironment(
  account: Readonly<Record<string, string>>,
  session: Readonly<Record<string, string>>,
): Readonly<Record<string, string>> {
  return { ...account, ...session };
}
