name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    name: GoReleaser Publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - name: Compile, package, and publish all channels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_PUSH_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
        run: nix develop .#releaser -c ./scripts/release/publish.sh
